# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['DEFAULT_VAGRANT_PROVIDER'] = 'virtualbox'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "debian8"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider :virtualbox do |v|
	v.gui = true
  end

  config.vm.synced_folder ".", "/vagrant"
  #config.vm.synced_folder "./data", "/server/ftp"
  #config.vm.synced_folder './config', '/opt/config'

  #config.vm.provision :shell, path: "config/setup.sh"

  config.vm.provision "shell", inline:
    $script = <<SCRIPT
SCRIPT


  config.vm.provision "shell", inline: 
    $script = <<SCRIPT
    echo Shell provisioning...
    sudo apt-get install puppet -y
SCRIPT

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.options = '--test'    # see the output
    #puppet.synced_folder_type = "9p"
    puppet.facter = {
      "user" => "user",
      "password" => "passwd",
    }
  end
end
